services:
  xmr-miner:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    container_name: xmr-miner
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - WALLET=8ApdEka2j6CUaaNKp12H1VBi1bziZB2T9Dhju1fPzgiTC8KBLWEEddVeZnpZjg7Ni4KCENsPLfSDfh2nbMhbFqngM5wKwHE
      - POOL_HOST=pool.supportxmr.com
      - POOL_PORT=3333
    restart: unless-stopped
